### ISSUE TITLE
wskdeploy runtime specification does not work with compose.

### ISSUE THREAD

**Issue by style95** [apache/openwhisk-devtools#279]
This kind of runtime specification does not work with a compose based setup
```
packages:
  hello_world_package:
    version: 1.0
    license: Apache-2.0
    actions:
      hello_world:
        function: src/hello.py
        runtime: python@3
```
while this manifest works as expected.

```
packages:
  hello_world_package:
    version: 1.0
    license: Apache-2.0
    actions:
      hello_world:
        function: src/hello.py
        runtime: python:3
```

Users need to specify the runtime in this format: `runtime:version`.
But `wskdeploy` guides it with `@`.
https://github.com/apache/openwhisk-wskdeploy/blob/master/specification/html/spec_actions.md#valid-runtime-names
