### ISSUE TITLE
I added standalone openwhisk docker image in yaml file but cannot access playground ui through it

### ISSUE THREAD

**Issue by Areej-Fatima** [apache/openwhisk-devtools#352]
I want to have playground functionality in docker-compose. Is it already provided because I cannot find anything refering to it in this repository. So I have placed standalone openwhisk which provides both cli and playground. So here is what I added in yaml file:
```
ui:
    image: openwhisk/standalone:nightly
    ports:
      - 3232:3232
    depends_on:
      - controller
    volumes:
      - ~/var/run/docker.sock:/var/run/docker.sock
```
All containers are then up and running including the `docker-compose_ui_1`. But when I try to see logs of this container, it says `ERROR: No such service: docker-compose_ui_1` Any clue, whether I'm on the right track or what I'm doing wrong. I needed the playground functionality in docker-compose deployment of openwhisk.
