### ISSUE TITLE
CLI of standalone and docker-compose deployment conflict

### ISSUE THREAD

**Issue by Areej-Fatima** [apache/openwhisk-devtools#354]
I wanted playground functionality in docker-compose. So I used standalone openwhisk which provides both cli and playground with docker-compose deployment. Here is my yaml file:
```
ui:
    image: openwhisk/standalone:nightly
    ports:
      - 3232:3232
    depends_on:
      - controller
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
Now that works fine, but there is conflict of CLIs. When I run code in playground, it gives this error
`info: command was unsuccessful, code: 125 (unsuccessful), stdout: , stderr: /usr/bin/docker: Error response from daemon: Conflict. The container name "/wsk0_9_prewarm_nodejs14" is already in use by container "9713edf3e8e5c81867250e1979a580c266912708a1216b58f41d9e0b339a4705". You have to remove (or rename) that container to be able to reuse that name.` And secondly, the CLI issues. How to link both the CLIs to run one instance of CLI only and playground UI linked with all other services of docker-compose.yml?
