### ISSUE TITLE
Error contacting service, status = undefined

### ISSUE THREAD

**Issue by Areej-Fatima** [apache/openwhisk-devtools#356]
I have a playground UI that I have build from this path `https://github.com/apache/openwhisk/tree/master/core/standalone/src/main/resources/playground` using nginx as base image which proxy_pass to ui/index.html. I used this image in this `https://github.com/apache/openwhisk-devtools/blob/master/docker-compose/docker-compose-lean.yml`. I can access UI via `ip-address:3232`. I'm now trying to link it to controller but when I try to run function in ui, I'm getting this error `Error contacting service, status = undefined`. I changed `API_HOST` in ui's code as `http://ip-address:8080` and namespace to guest.
My ui service looks like this in docker-compose.yml
```
ui:
    image: hub_username/repository:tag
    ports:
      - 3232:80
    depends_on:
      - controller
```
